/*
 * This file is generated by jOOQ.
*/
package com.monitoratec.springbasics.model.db;


import com.monitoratec.springbasics.model.db.tables.Authors;
import com.monitoratec.springbasics.model.db.tables.Books;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -893493413;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>AUTHORS</code>.
     */
    public final Authors AUTHORS = com.monitoratec.springbasics.model.db.tables.Authors.AUTHORS;

    /**
     * The table <code>BOOKS</code>.
     */
    public final Books BOOKS = com.monitoratec.springbasics.model.db.tables.Books.BOOKS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authors.AUTHORS,
            Books.BOOKS);
    }
}
