/*
 * This file is generated by jOOQ.
*/
package com.monitoratec.springbasics.model.db;


import com.monitoratec.springbasics.model.db.tables.Authors;
import com.monitoratec.springbasics.model.db.tables.Books;
import com.monitoratec.springbasics.model.db.tables.records.AuthorsRecord;
import com.monitoratec.springbasics.model.db.tables.records.BooksRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthorsRecord, Integer> IDENTITY_AUTHORS = Identities0.IDENTITY_AUTHORS;
    public static final Identity<BooksRecord, Integer> IDENTITY_BOOKS = Identities0.IDENTITY_BOOKS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = UniqueKeys0.KEY_AUTHORS_PRIMARY;
    public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = UniqueKeys0.KEY_BOOKS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BooksRecord, AuthorsRecord> BOOKS_IBFK_1 = ForeignKeys0.BOOKS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuthorsRecord, Integer> IDENTITY_AUTHORS = Internal.createIdentity(Authors.AUTHORS, Authors.AUTHORS.ID);
        public static Identity<BooksRecord, Integer> IDENTITY_BOOKS = Internal.createIdentity(Books.BOOKS, Books.BOOKS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = Internal.createUniqueKey(Authors.AUTHORS, "KEY_AUTHORS_PRIMARY", Authors.AUTHORS.ID);
        public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = Internal.createUniqueKey(Books.BOOKS, "KEY_BOOKS_PRIMARY", Books.BOOKS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BooksRecord, AuthorsRecord> BOOKS_IBFK_1 = Internal.createForeignKey(com.monitoratec.springbasics.model.db.Keys.KEY_AUTHORS_PRIMARY, Books.BOOKS, "BOOKS_ibfk_1", Books.BOOKS.AUTHOR_ID);
    }
}
