/*
 * This file is generated by jOOQ.
*/
package com.monitoratec.springbasics.model.db;


import com.monitoratec.springbasics.model.db.tables.Authors;
import com.monitoratec.springbasics.model.db.tables.Books;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AUTHORS</code>.
     */
    public static final Authors AUTHORS = com.monitoratec.springbasics.model.db.tables.Authors.AUTHORS;

    /**
     * The table <code>BOOKS</code>.
     */
    public static final Books BOOKS = com.monitoratec.springbasics.model.db.tables.Books.BOOKS;
}
